version: '3.8'

services:
  backend:
    build: ./backend
    container_name: magic-market-backend
    restart: always
    ports:
      - "8111:8111"
    env_file:
      - .env
    environment:
      - BMM_MYSQL_HOST=${BMM_MYSQL_HOST}
      - BMM_MYSQL_PORT=${BMM_MYSQL_PORT}
      - BMM_MYSQL_USER=${BMM_MYSQL_USER}
      - BMM_MYSQL_PASSWORD=${BMM_MYSQL_PASSWORD}
      - BMM_MYSQL_DATABASE=${BMM_MYSQL_DATABASE}
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: magic-market-frontend
    restart: always
    ports:
      - "82:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
